name: HelloWorld
version: '${project.version}'
main: org.coder_cat.helloworld.HelloWorld
api-version: '1.20'

commands:
   rtp:
      description: Teleports to a random location
      usage: /<command>
      permission: helloworld.rtp