name: SuperFood
version: '${project.version}'
author: Coder_Cat
description: A generic Slimefun4-Addon
website: https://github.com/SI-Abid/SuperFood

main: me.coder_cat.super_food.SuperFood
depend: [Slimefun]
api-version: '1.20'

commands:
  rtp:
    description: Teleports you to a random location
    usage: /rtp